### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by kristjanvalur**
Look here, no hands!

### CODE REVIEW

**Comment by mattig** [comment]
In the readme file, what is `settings.py`? Btw, do you mean `Pipfile.lock`?
See: **"When switching between version, you need to remove the `Pipfile` that gets created from the `settings.py` file."**

**Comment by mattig** [comment]
oops, wrong button. tis open still!

**Comment by kristjanvalur** [comment]
Oops, I meant `setup.py`  Will fix.
https://github.com/dgnorth/drift-config/blob/develop/setup.py

Because this is a library, it uses a setup.py to define its dependecencies for setuptools.
Pipfile and Pipfile.lock are 'application' deployment helpers.  Got me a while to get the difference, see

http://pipenv.readthedocs.io/en/latest/advanced/#pipfile-vs-setup-py

**Comment by mattig** [comment]
Quite nifty the **six** library, but if the plan would be to drop 2.7 support eventually would it make sense to actually go in and migrate from six to pure 3?
Example of sixness:
`from six.moves.urllib.parse import urlparse`
and
`for table_name, table_data in six.iteritems(self._tables):`
..and so on.

**Comment by kristjanvalur** [comment]
Once 2.7 support is dropped, sure.  While migrating, and you want to run in both places, keep it in.

We can drop six.iterietems() in most places, since having actual list created in 2.7 is not much of a performance issue.

**Comment by mattig** [comment]
[You hear that Mr. Anderson?... That is the sound of inevitability... It is the sound of your death... Goodbye, Mr. Anderson...](https://pythonclock.org/)
image

**Comment by kristjanvalur** [comment]
Codecov needs to be updated, apparently it is not excercising a lot of things.
Also, the automatic testing bots need to be updated to deal with py3

**Pull request merged**
